"""Generates lib/domain/spec/spec_data.dart from packages/layout_spec JSON so
the Dart layout engine and the TypeScript render service read identical data.

Usage: python tools/spec/sync_spec.py
A Dart test (test/domain/spec_sync_test.dart) fails if the output is stale.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC = ROOT / "packages" / "layout_spec"
OUT = ROOT / "apps" / "mobile" / "lib" / "domain" / "spec" / "spec_data.dart"


def dart_str(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$") + "'"


def dart_value(v) -> str:
    if isinstance(v, str):
        return dart_str(v)
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(float(v)) if isinstance(v, float) else str(v)
    if isinstance(v, list):
        return "[" + ", ".join(dart_value(x) for x in v) + "]"
    raise TypeError(v)


def main() -> None:
    formats = json.loads((SPEC / "formats.json").read_text(encoding="utf-8"))
    strings = json.loads((SPEC / "i18n" / "book_strings.json").read_text(encoding="utf-8"))
    lines = [
        "// GENERATED by tools/spec/sync_spec.py from packages/layout_spec. Do not edit.",
        "// ignore_for_file: require_trailing_commas, lines_longer_than_80_chars",
        "",
        "import 'book_format.dart';",
        "",
        f"const double kBleedMm = {float(formats['bleedMm'])};",
        f"const double kSafeOuterMm = {float(formats['safeOuterMm'])};",
        f"const double kSafeGutterMm = {float(formats['safeGutterMm'])};",
        f"const double kProviderSafeMm = {float(formats['providerSafeMm'])};",
        f"const String kDefaultFormatId = {dart_str(formats['defaultFormatId'])};",
        f"const String kTravelDefaultFormatId = {dart_str(formats['travelDefaultFormatId'])};",
        "",
        "const List<BookFormat> kBookFormats = [",
    ]
    for f in formats["formats"]:
        lines.append(
            "  BookFormat("
            f"id: {dart_str(f['id'])}, trimWMm: {float(f['trimWMm'])}, trimHMm: {float(f['trimHMm'])}, "
            f"binding: Binding.{f['binding']}, minPages: {f['minPages']}, maxPages: {f['maxPages']}, "
            f"hidden: {dart_value(f['hidden'])}),"
        )
    lines += ["];", "", "const Map<String, Map<String, Object>> kBookStrings = {"]
    for lang, entries in strings.items():
        lines.append(f"  {dart_str(lang)}: {{")
        for k, v in entries.items():
            if isinstance(v, list):
                lines.append(f"    {dart_str(k)}: <String>{dart_value(v)},")
            else:
                lines.append(f"    {dart_str(k)}: {dart_value(v)},")
        lines.append("  },")
    lines += ["};", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", OUT)
    # The app bundles its own copy of the fake-mode catalogue.
    assets = ROOT / "apps" / "mobile" / "assets" / "spec"
    assets.mkdir(parents=True, exist_ok=True)
    (assets / "catalog.json").write_text(
        (SPEC / "fixtures" / "catalog.json").read_text(encoding="utf-8"), encoding="utf-8"
    )
    print("copied catalog.json to", assets)


if __name__ == "__main__":
    main()
